'use client';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ReactNode } from 'react';
import { Provider } from 'react-redux';
import { store } from '@/redux/store';
import ChakraProvider from '@/providers/chakraProvider';
import Header from '@/components/header/Header';

const inter = Inter({ subsets: ['latin'] });

interface RootLayoutProps {
  children: ReactNode;
}

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider>
          <Provider store={store}>
            <Header />
            <main style={{ paddingTop: '75px' }}>
              {children}
            </main>
          </Provider>
        </ChakraProvider>
      </body>
    </html>
  );
}

