"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import { Provider } from "react-redux";
import { store, persistor } from '@/redux/store';
import { PersistGate } from 'redux-persist/integration/react';
import ChakraProvider from "@/providers/chakraProvider";
import Header from "@/components/header/Header";

const inter = Inter({ subsets: ["latin"] });

interface RootLayoutProps {
  children: ReactNode;
}

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider>
          <Provider store={store}>
          <PersistGate loading={null} persistor={persistor}>
              <Header />
              {children}
            </PersistGate>
          </Provider>
        </ChakraProvider>
      </body>
    </html>
  );
}
